# How to get/access elements of numpy array.
    -   there are two ways we can access elements of np array:
        1. Indexing: gives single element
        2. Slicing: Gives single/slice of array.

In [2]:
import numpy as np

In [5]:
a = np.array((10, 20, 30, 40, 50))
print(f"{a=}")
print(f"{a[0], a[1], a[2], a[3], a[4]}")
# numpy also supports negative indexing
print(f"{a[-1], a[-2], a[-3], a[-4], a[-5]}")

a=array([10, 20, 30, 40, 50])
(10, 20, 30, 40, 50)
(50, 40, 30, 20, 10)


In [9]:
# accessing elements from 2d-array
a = np.array(((10, 20, 30), (40, 50, 60), (70, 80, 90)))
print(f"{a=}")
print(f"{a[0][1]=}")
print(f"{a[-1][-1]=}")
# accessing 50
print(f"{a[1][1]=}")
print(f"{a[-2][-2]=}")


a=array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])
a[0][1]=20
a[-1][-1]=90
a[1][1]=50
a[-2][-2]=50


In [6]:
# accessing elements from 3d-array
a = np.arange(start=1, stop=28).reshape((3, 3, 3))
print(f"{a=}")
print(f"{a[0][1][1]=}")
print(f"{a[-1][-1]=}")
print(f"{a[1][1]=}")
print(f"{a[-2][-2]=}")
print(f"{a[1][-2]=}")
print(f"{a[-2][1]=}")

a=array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])
a[0][1][1]=5
a[-1][-1]=array([25, 26, 27])
a[1][1]=array([13, 14, 15])
a[-2][-2]=array([13, 14, 15])
a[1][-2]=array([13, 14, 15])
a[-2][1]=array([13, 14, 15])


In [9]:
np.where(a==29)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

# Slicing in python
-   If we want to take a piece of nd array, we must go for slice operator.
-   syntax for slicing is [start:stop:step]
-   It returns elements from start to (stop-1) index.
-   Default for
    -   begin => 0
    -   end =>  -1 or (length of array)
    -   step => 1


In [22]:
a = np.array((10, 20, 30, 40, 50, 60, 70))
print(f'{a[0:4]=}')
print(f'{a[2:6]=}')
print(f'{a[2:]=}')
print(f'{a[:-1]=}')
print(f'{a[-5:-1]=}')
print(f'{a[-5:7]=}')
print(f'{a[1:7:1]=}')
print(f'{a[1:7:-1]=}')
print(f'{a[7:1:-1]=}')


a[0:4]=array([10, 20, 30, 40])
a[2:6]=array([30, 40, 50, 60])
a[2:]=array([30, 40, 50, 60, 70])
a[:-1]=array([10, 20, 30, 40, 50, 60])
a[-5:-1]=array([30, 40, 50, 60])
a[-5:7]=array([30, 40, 50, 60, 70])
a[1:7:1]=array([20, 30, 40, 50, 60, 70])
a[1:7:-1]=array([], dtype=int64)
a[7:1:-1]=array([70, 60, 50, 40, 30])


In [24]:
            # 00, 01, 02, 03, 04, 05, 06, 07, 08, 09
a = np.array((10, 20, 30, 40, 50, 60, 70, 80, 90, 100))
            # -10, -9, -8, -7, -6, -5, -4, -3, -2, -1

print(f"{a[5:-10: 2]=}")
print(f"{a[5:-10: -2]=}")

a[5:-10: 2]=array([], dtype=int64)
a[5:-10: -2]=array([60, 40, 20])


# slice operator on 2d-arrays
    row             column
a[begin:end:step, begin:end:step]

In [32]:
a = np.arange(1, 7).reshape((3, 2))*10
# slicing is used to extract chunk from an array

print(f"{a[0, :]=}")
print(f"{a[0::2, :]=}")
print(f"{a[:2, 1:]=}")


a[0, :]=array([10, 20])
a[0::2, :]=array([[10, 20],
       [50, 60]])
a[:2, 1:]=array([[20],
       [40]])


In [41]:
a = np.arange(1, 17).reshape((4, 4))
# slicing is used to extract chunk from an array
print(f"{a[0:2, :]=}")
print(f"{a[::3, :]=}")
print(f"{a[:, 0:2]=}")
print(f"{a[:, ::2]=}")
print(f"{a[1:3, 1:3]=}")
print(f"{a[::3, ::3]=}")

a[0:2, :]=array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
a[::3, :]=array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])
a[:, 0:2]=array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])
a[:, ::2]=array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])
a[1:3, 1:3]=array([[ 6,  7],
       [10, 11]])
a[::3, ::3]=array([[ 1,  4],
       [13, 16]])


# Slice operator on 3d-arrays
- syntax:
    -   a[i_start:i_stop:i_step, j_start:j_stop:j_step, k_start:k_stop:k_step]

In [52]:
a = np.arange(1, 25).reshape((2, 3, 4))

print(f"{a[:,:,:1]}")
print(f"{a[:,0,:]}")
print(f"{a[:,::2,:]}")
print(f"{a[:,0:2:,1:3]}")
print(f"{a[:,::2,::3]}")

[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]
[[ 1  2  3  4]
 [13 14 15 16]]
[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [21 22 23 24]]]
[[[ 2  3]
  [ 6  7]]

 [[14 15]
  [18 19]]]
[[[ 1  4]
  [ 9 12]]

 [[13 16]
  [21 24]]]


# To select elements using slice operator, elements has to be in order, but to select elements arbitrary, we need to use advanced indexing.

-   By using index, we can access only one elements at a time.
-   By using slice operator we can access multiple elements at a time, but all elements has to be in order.
-   Now we want to select multiple elements, that are not in order.

# Syntax
- ### for 1d-array
    - array[x] 
        - x can be a nd-array or list, which represents required indexes
        - x can also be True/False, values(True represents keep, false repn not to keep value.)
- ### for 2d-array
    - array[[indexes_of_rows], [indexes_of_columns]] 
        - indexes can be a nd-array or list, which represents required indexes
        - indexes can also be True/False, values(True represents keep, false repn not to keep value.)


In [59]:
a = np.arange(10, 101, 10)
print(f"{a=}")
print(f"{a[[0, 4, 7, 2]]}") # this will return items in provided orders, element at index 2 will come after element at index 7.
print(f"{a[[True, False, True, False, True, False, False, True, False, False]]}")

a=array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
[10 50 80 30]
[10 30 50 80]


In [67]:
a = np.arange(1, 17).reshape((4,4))
print(f"{a=}")
print(f"{a[[0,1,2,3],[0,1, 2,3]]}") # diagonal
print(f"{a[[0,1,2,3,3,3,3],[0,0,0,0,1,2,3]]}") # L-Shape

a=array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
[ 1  6 11 16]
[ 1  5  9 13 14 15 16]


# Condition based selection:
-   We can select elements based on some condition also
-   Syntax:
    -   array[boolean_array]
        -   Whichever element of boolean_array is True corresponding element will be retained, others will be removed from final result.

In [70]:
a = np.arange(10, 41, 10)
print(f"{a=}")
bool_arr = [True, False, True, False]
print(f"{a[bool_arr]}")
# but length of boolean_arr must be equal to length of ndarray.


a=array([10, 20, 30, 40])
[10 30]


In [85]:
a = np.arange(10, 101, 10)
print(f"{a=}")
# elements greater than 45
print(f"{a[a>45]}")
# even numbers
print(f"{a[a%2 == 0]}")
# odd numbers
print(f"{a[a%2 != 0]}")
# divisible by 5
print(f"{a[a%5==0]}")

a=array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
[ 50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[]
[ 10  20  30  40  50  60  70  80  90 100]


In [84]:
a = np.arange(10, 101, 10).reshape((2,5))
print(f"{a=}")
# elements greater than 45
print(f"{a[a>45]}")
# even numbers
print(f"{a[a%2 == 0]}")
# odd numbers
print(f"{a[a%2 != 0]}")
# divisible by 5
print(f"{a[a%5==0]}")

a=array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])
[ 50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[]
[ 10  20  30  40  50  60  70  80  90 100]
