# ndenumerate
-   Main advantage of ndenumerate function is if we want to find coordinates as well elements, we must use this.
-   this fucntion returns multi-dimensional array iterator, which contains array indices and its values.

In [7]:
import  numpy as np

In [8]:
# 1d-array
a = np.arange(10, 71, 10)
for pos, el in np.ndenumerate(a):
    print(pos, "=>", el)

(0,) => 10
(1,) => 20
(2,) => 30
(3,) => 40
(4,) => 50
(5,) => 60
(6,) => 70


In [9]:
# 1d-array
a = np.arange(10, 81, 10).reshape((2, 2, 2))
for pos, el in np.ndenumerate(a):
    print(pos, "=>", el)

(0, 0, 0) => 10
(0, 0, 1) => 20
(0, 1, 0) => 30
(0, 1, 1) => 40
(1, 0, 0) => 50
(1, 0, 1) => 60
(1, 1, 0) => 70
(1, 1, 1) => 80


# Arithmetic Operators
-   +, -, *, /, //, %, **

In [16]:
# 1d-array
a = np.arange(10, 71, 10)
print(f"{a=}")
print(f"{a+2=}")
print(f"{a-2=}")
print(f"{a*2=}")
print(f"{a/2=}")
print(f"{a//2=}")
print(f"{a**2=}")

a=array([10, 20, 30, 40, 50, 60, 70])
a+2=array([12, 22, 32, 42, 52, 62, 72])
a-2=array([ 8, 18, 28, 38, 48, 58, 68])
a*2=array([ 20,  40,  60,  80, 100, 120, 140])
a/2=array([ 5., 10., 15., 20., 25., 30., 35.])
a//2=array([ 5, 10, 15, 20, 25, 30, 35])
a**2=array([ 100,  400,  900, 1600, 2500, 3600, 4900])


## to perform arithmetic operations on nd arrays, their shape and size must be same.

In [18]:
a = np.array((10, 20, 30, 40))
b = np.array((1, 2, 3, 4))
print(f"{a+b}")
print(f"{a-b}")
print(f"{a*b}")
print(f"{a/b}")
print(f"{a**b}")

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[     10     400   27000 2560000]


In [19]:
a = np.array((10, 20, 30, 40))
b = np.array((1, 2, 3, 4, 5))
print(f"{a+b}")
print(f"{a-b}")
print(f"{a*b}")
print(f"{a/b}")
print(f"{a**b}")

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [20]:
a = np.array(((10, 20, 30), (40, 50, 60)))
b = np.array(((1, 2, 3), (4, 5, 6)))
print(f"{a+b}")
print(f"{a-b}")
print(f"{a*b}")
print(f"{a/b}")
print(f"{a**b}")

[[11 22 33]
 [44 55 66]]
[[ 9 18 27]
 [36 45 54]]
[[ 10  40  90]
 [160 250 360]]
[[10. 10. 10.]
 [10. 10. 10.]]
[[         10         400       27000]
 [    2560000   312500000 46656000000]]


In [22]:
a = np.array((((10, 20, 30), (40, 50, 60)), ((70, 80, 90), (100, 110, 120))))
b = np.array((((1, 2, 3), (4, 5, 6)), ((7, 8, 9), (10, 11, 12))))
print(f"{a+b=}")
print(f"{a-b=}")
print(f"{a*b=}")
print(f"{a/b=}")
print(f"{a**b=}")

a+b=array([[[ 11,  22,  33],
        [ 44,  55,  66]],

       [[ 77,  88,  99],
        [110, 121, 132]]])
a-b=array([[[  9,  18,  27],
        [ 36,  45,  54]],

       [[ 63,  72,  81],
        [ 90,  99, 108]]])
a*b=array([[[  10,   40,   90],
        [ 160,  250,  360]],

       [[ 490,  640,  810],
        [1000, 1210, 1440]]])
a/b=array([[[10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.]]])
a**b=array([[[                  10,                  400,
                        27000],
        [             2560000,            312500000,
                  46656000000]],

       [[       8235430000000,     1677721600000000,
           387420489000000000],
        [ 7766279631452241920, -5946020928676349952,
         -4172562995806732288]]])
