### How to crteate numpy arrays: 
    - array()
    - arange()
    - linspace()
    - zeroes()
    - ones()
    - full()
    - eye()
    - identity()
    - empty()
    - numpy.random
        - randint()
        - rand()
        - uniform()
        - randn()
        - normal()
        - shuffle()
    
    etc...


## 1. array()
for the given list or tuple, if we want to create an array, we use array function.

In [1]:
import numpy as np

In [2]:
ls = [1, 2, 3,4, 5]

In [10]:
a = np.array(ls)
print(np.array(ls))
print(np.array(ls, dtype=int))
print(np.array(ls, dtype=str))
print(np.array(ls, copy=True))
print(np.array(ls, order='K'))
print(np.array(ls, order='A'))
print(np.array(ls, order='C'))
print(np.array(ls, order='F'))

[1 2 3 4 5]
[1 2 3 4 5]
['1' '2' '3' '4' '5']
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [15]:
print(a.ndim) # dimension of array
print(a.dtype) # data type of elements in array
print(a.shape) # shape of array

1
int32
(5,)


In [18]:
# creating 2d-array
mtrix = [[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 100, 100]]
a = np.array(mtrix)

In [20]:
print(a.ndim) # dimension of array
print(a.dtype) # data type of elements in array
print(a.shape) # shape of array
print(a.size) # total number of elelments in array

2
int32
(4, 3)
12
